openapi: 3.0.0
info:
  title: MT_VIS
  version: '1.0'
  description: MT_VIS api
servers:
  - url: 'http://localhost:3000'
paths:
  '/soknader/{soknadsid}':
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ''
      operationId: get-soknader
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
    parameters:
      - schema:
          type: string
        name: soknadsid
        in: path
        required: true
    patch:
      summary: ''
      operationId: patch-soknader-id
      responses:
        '200':
          description: OK
  '/soknader/{soknadsid}/vedtak/{vedtaksid}':
    parameters:
      - schema:
          type: string
        name: soknadsid
        in: path
        required: true
      - schema:
          type: string
        name: vedtaksid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/vedtak'
      operationId: get-soknader-id-vedtak
    patch:
      summary: ''
      operationId: patch-soknader-id-vedtak
      responses:
        '200':
          description: OK
    delete:
      summary: ''
      operationId: delete-soknader-id-vedtak-id
      responses:
        '200':
          description: OK
  '/soknader/{soknadsid}/biometriopptak/{biometriopptakid}':
    parameters:
      - schema:
          type: string
        name: soknadsid
        in: path
        required: true
      - schema:
          type: string
        name: biometriopptakid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/biometriopptak'
      operationId: get-soknader-id-biometriopptak-id
      description: ''
    delete:
      summary: ''
      operationId: delete-soknader-id-biometriopptak-id
      responses:
        '202':
          description: Accepted
  /soknader:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/soknad'
      operationId: get-soknader
      parameters:
        - schema:
            type: string
          in: query
          name: gruppe
        - schema:
            type: string
          in: query
          name: visumnummer
    post:
      summary: ''
      operationId: post-soknader
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/soknad'
  '/soknader/{soknadsid}/vedtak':
    parameters:
      - schema:
          type: string
        name: soknadsid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/vedtak'
      operationId: get-soknader-soknadsid-vedtak
    post:
      summary: ''
      operationId: post-soknader-soknadsid-vedtak
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/vedtak'
  '/soknader/{sokndsid}/biometriopptak':
    parameters:
      - schema:
          type: string
        name: sokndsid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/biometriopptak'
      operationId: get-soknader-sokndsid-biometriopptak
    post:
      summary: ''
      operationId: post-soknader-sokndsid-biometriopptak
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/biometriopptak'
  '/soknader/{soknadsid}/dossier':
    parameters:
      - schema:
          type: string
        name: soknadsid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dossier'
      operationId: get-soknader-soknadsid-dossier
    delete:
      summary: ''
      operationId: delete-soknader-soknadsid-dossier
      responses:
        '200':
          description: OK
    post:
      summary: ''
      operationId: post-soknader-soknadsid-dossier
      responses:
        '200':
          description: OK
  '/meldinger/{meldingsid}':
    parameters:
      - schema:
          type: string
        name: meldingsid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/melding'
      operationId: get-meldinger-id
    patch:
      summary: ''
      operationId: patch-meldinger-id
      responses:
        '200':
          description: OK
      description: 'Legge melding tilbake på kø, brukes hvis noe har feilet'
      requestBody:
        description: ''
  /meldinger:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/melding'
      operationId: get-meldinger
      parameters:
        - schema:
            type: string
          in: query
          name: status
        - schema:
            type: string
          in: query
          name: system
        - schema:
            type: string
          in: query
          name: soknadsid
        - schema:
            type: string
          in: query
          name: vedtaksid
        - schema:
            type: number
          in: query
          name: antallDagerTilbakeITid
          description: ''
      requestBody: {}
  /myndigheter:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/myndighet'
      operationId: get-myndigheter
      parameters:
        - schema:
            type: string
          in: query
          name: etat
        - schema:
            type: string
          in: query
          name: brukernavn
  /sok:
    get:
      summary: ''
      operationId: get-sok
      responses:
        '200':
          description: OK
      description: synkront søk mot vis
  /sokFingeravtrykk:
    post:
      summary: ''
      operationId: post-sokFingeravtrykk
      responses:
        '200':
          description: OK
      description: asynkront søk fingeravtrykk
  /verifiserFingeravtrykk:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-verifyFingeravtrykk
      description: synkron verifisering av fingeravtrykk oppmot noe
    parameters: []
  '/visa/{visaId}':
    parameters:
      - schema:
          type: string
        name: visaId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/visum'
      operationId: get-visa-visaId
  /visa:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/visum'
      operationId: get-visa
      parameters:
        - schema:
            type: string
          in: query
          name: gruppe
components:
  schemas:
    soknad:
      title: soknad
      type: object
      properties:
        id:
          type: string
    vedtak:
      title: vedtak
      type: object
      properties:
        id:
          type: string
    visum:
      title: visum
      type: object
      properties:
        id:
          type: string
    ansiktsfoto:
      title: ansiktsfoto
      type: object
      properties:
        id:
          type: string
    fingeravtrykk:
      title: fingeravtrykk
      type: object
      properties:
        id:
          type: string
    myndighet:
      title: myndighet
      type: object
      properties:
        id:
          type: string
    gruppe:
      title: gruppe
      type: object
      properties:
        id:
          type: string
        soknader:
          type: array
          items:
            $ref: '#/components/schemas/soknad'
        isFamilie:
          type: boolean
    formaal:
      title: rolle
      type: object
      properties:
        id:
          type: string
    melding:
      title: melding
      type: object
      properties:
        id:
          type: string
    biometriopptak:
      title: biometriopptak
      oneOf:
        - $ref: '#/components/schemas/fingeravtrykk'
        - $ref: '#/components/schemas/ansiktsfoto'
    dossier:
      title: dossier
      type: array
      items:
        $ref: '#/components/schemas/soknad'
